repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: debug-statements
      - id: check-merge-conflict

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.12.12
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format



  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.8.0
  #   hooks:
  #     - id: mypy
  #       language_version: python3.13
  #       args:
  #       - --install-types
  #       - --non-interactive
  #       - --ignore-missing-imports
  #       exclude: |
  #         ^(tests|docs|examples)/.*$|
  #         conftest\.py$
