GALLERY_NAME_MAX_LENGTH = 128
PHOTO_SEARCH_MAX_LENGTH = 128
GALLERY_PRIVATE_NOTES_MAX_LENGTH = 1000
GALLERY_PUBLIC_DESCRIPTION_MAX_LENGTH = 255
PUBLIC_GALLERY_SORT_BY_DEFAULT = "original_filename"
PUBLIC_GALLERY_SORT_ORDER_DEFAULT = "asc"
