"""add index by gallery to photo

Revision ID: 85fe4b397142
Revises: 7b1a2c3d4e5f
Create Date: 2026-01-25 20:31:19.060609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85fe4b397142'
down_revision: Union[str, Sequence[str], None] = '7b1a2c3d4e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_photos_gallery_id'), 'photos', ['gallery_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photos_gallery_id'), table_name='photos')
    # ### end Alembic commands ###
