"""add non destructive photo rotation

Revision ID: 1174ab994e82
Revises: d4e5f6a7b8c9
Create Date: 2026-10-04 11:42:29.118669

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1174ab994e82"
down_revision: str | Sequence[str] | None = "d4e5f6a7b8c9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("photos", sa.Column("rotation", sa.SmallInteger(), server_default="0", nullable=False))
    op.add_column("photos", sa.Column("requested_rotation", sa.SmallInteger(), server_default="0", nullable=False))
    op.add_column("photos", sa.Column("rotation_revision", sa.Integer(), server_default="0", nullable=False))
    op.add_column("photos", sa.Column("rotated_object_key", sa.String(), nullable=True))
    op.add_column("photos", sa.Column("rotation_status", sa.String(length=16), server_default="ready", nullable=False))
    op.add_column("photos", sa.Column("rotation_error", sa.Text(), nullable=True))
    op.add_column("photos", sa.Column("rotation_updated_at", sa.DateTime(), nullable=True))
    op.create_index("ix_photos_rotation_status_updated_at", "photos", ["rotation_status", "rotation_updated_at"], unique=False)
    op.create_check_constraint("ck_photos_requested_rotation", "photos", "requested_rotation IN (0, 90, 180, 270)")
    op.create_check_constraint("ck_photos_rotation", "photos", "rotation IN (0, 90, 180, 270)")
    op.create_check_constraint("ck_photos_rotation_revision", "photos", "rotation_revision >= 0")
    op.create_check_constraint("ck_photos_rotation_status", "photos", "rotation_status IN ('ready', 'pending', 'processing', 'failed')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_photos_rotation_status", "photos", type_="check")
    op.drop_constraint("ck_photos_rotation_revision", "photos", type_="check")
    op.drop_constraint("ck_photos_rotation", "photos", type_="check")
    op.drop_constraint("ck_photos_requested_rotation", "photos", type_="check")
    op.drop_index("ix_photos_rotation_status_updated_at", table_name="photos")
    op.drop_column("photos", "rotation_updated_at")
    op.drop_column("photos", "rotation_error")
    op.drop_column("photos", "rotation_status")
    op.drop_column("photos", "rotated_object_key")
    op.drop_column("photos", "rotation_revision")
    op.drop_column("photos", "requested_rotation")
    op.drop_column("photos", "rotation")
    # ### end Alembic commands ###
