"""share links lifecycle and daily analytics

Revision ID: e5b2b1912b0d
Revises: c4d8e1f2a9b0
Create Date: 2026-03-28 21:18:20.934042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5b2b1912b0d'
down_revision: Union[str, Sequence[str], None] = 'c4d8e1f2a9b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('share_link_daily_stats',
    sa.Column('sharelink_id', sa.UUID(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('views_total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('views_unique', sa.Integer(), server_default='0', nullable=False),
    sa.Column('zip_downloads', sa.Integer(), server_default='0', nullable=False),
    sa.Column('single_downloads', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sharelink_id'], ['share_links.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sharelink_id', 'day', name='pk_share_link_daily_stats')
    )
    op.create_table('share_link_daily_visitors',
    sa.Column('sharelink_id', sa.UUID(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('visitor_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sharelink_id'], ['share_links.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sharelink_id', 'day', 'visitor_hash', name='pk_share_link_daily_visitors')
    )
    op.add_column('share_links', sa.Column('label', sa.String(length=127), nullable=True))
    op.add_column('share_links', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('share_links', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.execute('UPDATE share_links SET updated_at = COALESCE(created_at, now()) WHERE updated_at IS NULL')
    op.alter_column('share_links', 'updated_at', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('share_links', 'updated_at')
    op.drop_column('share_links', 'is_active')
    op.drop_column('share_links', 'label')
    op.drop_table('share_link_daily_visitors')
    op.drop_table('share_link_daily_stats')
    # ### end Alembic commands ###
