"""Add Photo.status

Revision ID: 0d1edea3e426
Revises: 704453e0c15a
Create Date: 2026-01-17 22:18:15.028049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d1edea3e426'
down_revision: Union[str, Sequence[str], None] = '704453e0c15a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('status', sa.SmallInteger(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'status')
    # ### end Alembic commands ###
