"""add photo display_name

Revision ID: 17a031c9d6cd
Revises: 0d8b5cd635e9
Create Date: 2026-03-01 15:08:19.250952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17a031c9d6cd'
down_revision: Union[str, Sequence[str], None] = '0d8b5cd635e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('display_name', sa.String(), nullable=True))
    op.execute("UPDATE photos SET display_name = split_part(object_key, '/', -1)")
    op.alter_column('photos', 'display_name', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'display_name')
    # ### end Alembic commands ###
