"""add_thumbnail_outbox_dedup_index

Revision ID: 2340553a4e90
Revises: 59e1f37cc0dc
Create Date: 2026-06-20 00:23:45.204098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2340553a4e90'
down_revision: Union[str, Sequence[str], None] = '59e1f37cc0dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_thumbnail_outbox_unprocessed_photo_key', 'thumbnail_outbox', ['photo_id', 'object_key'], unique=True, postgresql_where=sa.text('processed = false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_thumbnail_outbox_unprocessed_photo_key', table_name='thumbnail_outbox', postgresql_where=sa.text('processed = false'))
    # ### end Alembic commands ###
