"""add media fields to photos

Revision ID: 78f6a5e87b23
Revises: 703516a7aa97
Create Date: 2026-07-11 22:42:45.248637

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '78f6a5e87b23'
down_revision: str | Sequence[str] | None = '703516a7aa97'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add new columns as nullable first
    op.add_column('photos', sa.Column('media_type', sa.String(length=16), nullable=True))
    op.add_column('photos', sa.Column('source_content_type', sa.String(length=128), nullable=True))
    op.add_column('photos', sa.Column('playback_object_key', sa.String(), nullable=True))
    op.add_column('photos', sa.Column('duration_ms', sa.Integer(), nullable=True))
    op.add_column('photos', sa.Column('processing_error', sa.Text(), nullable=True))

    # 2. Backfill existing rows: set media_type = 'image'
    op.execute("UPDATE photos SET media_type = 'image' WHERE media_type IS NULL")

    # 3. Set media_type NOT NULL with server default
    op.alter_column('photos', 'media_type',
                    existing_type=sa.String(length=16),
                    nullable=False,
                    server_default='image')

    # 4. Add CHECK constraints
    op.create_check_constraint(
        'ck_photos_media_type', 'photos',
        "media_type IN ('image', 'video')")
    op.create_check_constraint(
        'ck_photos_duration_ms_nonnegative', 'photos',
        'duration_ms >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Reverse order: drop constraints, then columns
    op.drop_constraint('ck_photos_duration_ms_nonnegative', 'photos', type_='check')
    op.drop_constraint('ck_photos_media_type', 'photos', type_='check')
    op.drop_column('photos', 'processing_error')
    op.drop_column('photos', 'duration_ms')
    op.drop_column('photos', 'playback_object_key')
    op.drop_column('photos', 'source_content_type')
    op.drop_column('photos', 'media_type')
    # ### end Alembic commands ###
