"""add project appearance and cover photo

Revision ID: 703516a7aa97
Revises: b1c2d3e4f5a6
Create Date: 2026-07-09 00:37:53.223701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '703516a7aa97'
down_revision: Union[str, Sequence[str], None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('cover_photo_id', sa.UUID(), nullable=True))
    op.add_column('projects', sa.Column('cover_focal_x', sa.Float(), server_default='50', nullable=False))
    op.add_column('projects', sa.Column('cover_focal_y', sa.Float(), server_default='50', nullable=False))
    op.add_column('projects', sa.Column('cover_display_option', sa.String(length=32), server_default='centered_title', nullable=False))
    op.add_column('projects', sa.Column('public_photo_spacing', sa.String(length=16), server_default='medium', nullable=False))
    op.add_column('projects', sa.Column('public_color_scheme', sa.String(length=16), server_default='light', nullable=False))
    # Data backfill: copy appearance + cover from first gallery per project
    op.execute("""
        UPDATE projects p
        SET cover_photo_id = g.cover_photo_id,
            cover_focal_x = g.cover_focal_x,
            cover_focal_y = g.cover_focal_y,
            cover_display_option = g.cover_display_option,
            public_photo_spacing = g.public_photo_spacing,
            public_color_scheme = g.public_color_scheme
        FROM (
            SELECT DISTINCT ON (project_id) project_id, cover_photo_id,
                cover_focal_x, cover_focal_y, cover_display_option,
                public_photo_spacing, public_color_scheme
            FROM galleries
            WHERE project_id IS NOT NULL AND is_deleted = false
            ORDER BY project_id, project_position ASC
        ) g
        WHERE g.project_id = p.id
    """)
    op.create_check_constraint('ck_projects_cover_focal_x_range', 'projects', 'cover_focal_x >= 0 AND cover_focal_x <= 100')
    op.create_check_constraint('ck_projects_cover_focal_y_range', 'projects', 'cover_focal_y >= 0 AND cover_focal_y <= 100')
    op.create_check_constraint('ck_projects_cover_display_option', 'projects', "cover_display_option IN ('centered_title', 'text_block', 'minimalist')")
    op.create_check_constraint('ck_projects_public_photo_spacing', 'projects', "public_photo_spacing IN ('small', 'medium', 'large')")
    op.create_check_constraint('ck_projects_public_color_scheme', 'projects', "public_color_scheme IN ('light', 'dark')")
    op.create_foreign_key('projects_cover_photo_id_fkey', 'projects', 'photos', ['cover_photo_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('projects_cover_photo_id_fkey', 'projects', type_='foreignkey')
    op.drop_constraint('ck_projects_public_color_scheme', 'projects', type_='check')
    op.drop_constraint('ck_projects_public_photo_spacing', 'projects', type_='check')
    op.drop_constraint('ck_projects_cover_display_option', 'projects', type_='check')
    op.drop_constraint('ck_projects_cover_focal_y_range', 'projects', type_='check')
    op.drop_constraint('ck_projects_cover_focal_x_range', 'projects', type_='check')
    op.drop_column('projects', 'public_color_scheme')
    op.drop_column('projects', 'public_photo_spacing')
    op.drop_column('projects', 'cover_display_option')
    op.drop_column('projects', 'cover_focal_y')
    op.drop_column('projects', 'cover_focal_x')
    op.drop_column('projects', 'cover_photo_id')
    # ### end Alembic commands ###
