"""add share_links table

Revision ID: 6eb0dedabb47
Revises: 2d73e7b5cff7
Create Date: 2025-07-22 18:25:46.839811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eb0dedabb47'
down_revision: Union[str, Sequence[str], None] = '2d73e7b5cff7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('galleries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_galleries_owner_id'), 'galleries', ['owner_id'], unique=False)
    op.create_table('photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gallery_id', sa.UUID(), nullable=False),
    sa.Column('url_s3', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gallery_id'], ['galleries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('share_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gallery_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('zip_downloads', sa.Integer(), nullable=False),
    sa.Column('single_downloads', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gallery_id'], ['galleries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('share_links')
    op.drop_table('photos')
    op.drop_index(op.f('ix_galleries_owner_id'), table_name='galleries')
    op.drop_table('galleries')
    # ### end Alembic commands ###
